### ISSUE TITLE
win10 pip install失败

### ISSUE THREAD

**Issue by leafleave** [pa4373/subhd.py#5]
PS C:\Users\leafl> pip install subhd.py
Collecting subhd.py
  Using cached subhd.py-0.1.4.tar.gz
Collecting beautifulsoup4==4.3.2 (from subhd.py)
  Using cached beautifulsoup4-4.3.2.tar.gz
Collecting chardet==2.3.0 (from subhd.py)
  Using cached chardet-2.3.0-py2.py3-none-any.whl
Collecting guessit==0.9.4 (from subhd.py)
  Using cached guessit-0.9.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\leafl\AppData\Local\Temp\pip-build-3u_cqoke\guessit\setup.py", line 28, in <module>
        HISTORY = open(os.path.join(here, 'HISTORY.rst')).read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 575: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\leafl\AppData\Local\Temp\pip-build-3u_cqoke\guessit\

请问怎么办？

**Comment by tomdog2016** [comment]
Download  subhd.py-master.zip, release it in some folder, then open setup.py using editor, change 'guessit==0.9.4' to 'guessit==3.0.3', after saved setup.py, run command line window，go to the directory of the file setup.py， type "python setup.py install", then press enter.
